#!/bin/bash
 
# Dependencies:
# imagemagick
# i3lock-color-git
# scrot
# mpc
 
IMAGE=/tmp/lock.png
 
# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x5" # 7.52s
#BLURTYPE="0x2" # 4.39s
#BLURTYPE="5x3" # 3.80s
#BLURTYPE="2x8" # 2.90s
#BLURTYPE="2x3" # 2.92s
BLURTYPE="0x5"

MPCPAUSE=false
if mpc status | grep playing; then
	mpc pause
	MPCPAUSE=true;
fi

scrot $IMAGE
#convert $IMAGE -sample 10% - | convert - -fill black -colorize 50% -scale 1000% $IMAGE
#composite -gravity center ~/.i3/lock-dual.png $IMAGE $IMAGE
convert $IMAGE -blur $BLURTYPE - | composite -gravity center ~/.i3/lock.png - $IMAGE
$(
i3lock --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c  -i $IMAGE -n

rm $IMAGE
xset -dpms
xset s off

if $MPCPAUSE; then	 
	mpc play;
fi
)&
sleep 1
