#!/bin/bash
 
# Dependencies:
# imagemagick
# i3lock-color-git
 
IMAGE=/tmp/lock.png

cp ~/bg $IMAGE
composite -gravity center ~/.i3/lock.png $IMAGE $IMAGE
i3lock --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c  -i $IMAGE
rm $IMAGE
xset -dpms
xset s off
